# 1. Pulling HTTPD Alpine Image 2.4.41

# FROM httpd@sha256:f2f1351f32ac7746a7ebaf6c025f5e99ccbde13d0d2a8aa8bdf9cc3aa440490c

FROM alpine

USER root

RUN apk update && \
  apk add python3 python3-dev libc-dev libxml2-dev libxslt-dev gcc && \
  pip3 --no-cache-dir install requests lxml google beautifulsoup4 && \
  mkdir /home/chatbot && mkdir /home/chatbot/public && \
  rm -rf /var/cache/apk/*

COPY public /home/chatbot/public/
COPY chatBot.py /home/chatbot
COPY server.py /home/chatbot

WORKDIR /home/chatbot

CMD [ "/usr/bin/python3", "/home/chatbot/server.py" ]

EXPOSE 8080