# 1. Pulling HTTPD Alpine Image 2.4.41

# FROM httpd@sha256:f2f1351f32ac7746a7ebaf6c025f5e99ccbde13d0d2a8aa8bdf9cc3aa440490c

FROM alpine

USER root

RUN apk update && \

  apk add python3 python3-dev libc-dev libxml2-dev libxslt-dev gcc && \
  pip3 install requests lxml google beautifulsoup4

